auto_save: false
display_label_popup: true
instance_label_auto_increment: true
store_data: true
keep_prev: false
logger_level: info

flags: null
label_flags:
  .*: [occluded, truncated]

labels:
  bike: null
  bus: null
  car: null
  motor: null
  train: null
  truck: null
  rider: null
  person: null
  traffic light: [
    red,
    yellow,
    blue,
    unknown
  ]
  traffic sign: [
    speed limit,
    end speed limit,
    stop,
    no entry,
    right turn,
    left turn,
    keep straight,
    keep left,
    keep right,
    traffic cone,
    other signs
  ]
  driveway(可行驶区域): [
    current,
    alternative
  ]
  lane:
    directions: [horizontal, vertical]
    type: [
      curb,
      single yellow,
      double yellow,
      single white,
      double white,
      crossing
    ]
    line type: [dotted, solid]

label_color:
  bike: 0xFFB300 # Vivid Yellow
  bus: 0x803E75 # Strong Purple
  car: 0xFF6800 # Vivid Orange
  motor: 0xA6BDD7 # Very Light Blue
  train: 0xC10020 # Vivid Red
  truck: 0xCEA262 # Grayish Yellow
  rider: 0x817066 # Medium Gray
  person: 0x007D34 # Vivid Green
  traffic light: 0xF6768E # Strong Purplish Pink
  traffic sign: 0x00538A # Strong Blue
  driveway(可行驶区域): 0xFF7A5C # Strong Yellowish Pink
  lane: 0x53377A # Strong Violet

file_search: null
sort_labels: true
validate_label: null

# main
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

epsilon: 10.0

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete

  open_next: [D, Ctrl+Shift+D]
  open_prev: [A, Ctrl+Shift+A]

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  add_point: Ctrl+Shift+P
  create_polygon: Ctrl+N
  create_rectangle: Ctrl+R
  create_circle: null
  create_line: null
  create_point: null
  create_linestrip: null
  edit_polygon: Ctrl+J
  delete_polygon: Delete
  duplicate_polygon: Ctrl+D
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, Backspace]
  edit_label: Ctrl+E
  edit_line_color: Ctrl+L
  edit_fill_color: Ctrl+Shift+L
  toggle_keep_prev_mode: Ctrl+P
